Minor correction for passwdGen_v2
Fixed error message associated with invalid password length.

diff --git a/passwdGen b/passwdGen
--- a/passwdGen
+++ b/passwdGen
@@ -87,7 +87,7 @@ getNumber()
               then
                 PASSWD_LENGTH="$OPTARG"
               else
-                echo "    ** Invalid value for password length [ -$OPTARG ] **" >&2
+                echo "    ** Invalid value for password length [ $OPTARG ] **" >&2
                 scriptUsage 1
             fi
         ;;
